# Minimal, single-line Spaceship prompt.
SPACESHIP_PROMPT_ORDER=(
  dir
  char
)
SPACESHIP_RPROMPT_ORDER=()

SPACESHIP_PROMPT_ASYNC=false
SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_PROMPT_SEPARATE_LINE=false
